language: rust

os:
  - linux
  - osx

# If you change this, you must also change README and Common.mk
rust:
  - nightly-2016-07-29

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq gcc-arm-embedded; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo install rustfmt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap px4/px4; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc-arm-none-eabi; fi
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      find -path ./extern -prune -o -name '*.rs' -exec rustfmt --write-mode=diff {} +; fi
  - make -C boards/storm
  - make -C boards/nrf51dk
  - make -C userland/libtock TOCK_ARCH=cortex-m4
  - make -C userland/examples/blink TOCK_ARCH=cortex-m4

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1ba4725f2c3035cb4966
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
