[package]
name = "crypto"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

build = "build.rs"

[dependencies]
rust-libcore = "*"
cortexm4 = { path = "../arch/cortex-m4" }
kernel = { path = "../kernel" }

[build-dependencies]
gcc = "0.3"
